//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abobus228.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Material
    {
        public int IdArticul { get; set; }
        public int Id_Material { get; set; }
        public Nullable<int> Required_amount_of_material { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_for_Agent Product_for_Agent { get; set; }
    }
}
