//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abobus228.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Products_Material = new HashSet<Products_Material>();
        }
    
        public int Id_Material { get; set; }
        public string Name_Material { get; set; }
        public int Id_Type { get; set; }
        public Nullable<int> Count_of_Paskages { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Count_in_Stock { get; set; }
        public Nullable<int> Minimum_possible_balance { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Type_Material Type_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Material> Products_Material { get; set; }
    }
}
